### ISSUE TITLE
Slow generation with jdk 1.8.0_66

### ISSUE THREAD

**Issue by blured75** [roybailey/sparkjava-retrofit-react#3]
With JDK1.8.0_66 the average time for generating ReactDashboard is 1 second which seems huge. Did you seen the same treatment time ?

Regards,
Blured.

**Comment by roybailey** [comment]
I remember the first time load was very slow but I thought it got faster after that.  It's a long time since I put this together and the last time I span it up it didn't work with latest Java8 version but I have no time to investigate further.  This was just a 'because you can' exercise, best you decide what if any value from it for any real world use.

...Roy
